language: node_js
node_js: "9"
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn 
script:
- yarn lint
- ./scripts/check-yarn-lock.sh
