# App config schema

translations.en."home.hero_blurb" = { category = "translations", type = "string", name = "Hero Blurb", description = "Blurb displayed on the front page." }
translations.en."settings.community" = { category = "translations", type = "string", name = "Community Prompt", description = "Prompt for joining your community." }
translations.en."app-name" = { category = "translations", type = "string", name = "App Name", description = "Name used across the app." }
translations.en."company-name" = { category = "translations", type = "string", name = "Company Name", description = "Company name used across the app." }
translations.en."app-short-domain" = { category = "translations", type = "string", name = "Short App Domain", description = "Short app domain." }
translations.en."contact-email" = { category = "translations", type = "string", name = "Contact email", description = "General contact email." }
translations.en."share-hashtag" = { category = "translations", type = "string", name = "Share Hashtag", description = "Hashtag used in share messages." }

features.show_terms = { category = "features", type = "boolean", name = "Show Terms of Use", description = "Show links to the terms of use." }
features.show_privacy = { category = "features", type = "boolean", name = "Show Privacy Notice", description = "Show links to the privacy notice." }
features.show_controls_link = { category = "features", type = "boolean", name = "Show Controls Links", description = "Show links to controls documentation." }
features.show_features_link = { category = "features", type = "boolean", name = "Show Features Links", description = "Show links to features documentation." }
features.show_community_link = { category = "features", type = "boolean", name = "Show Community Links", description = "Show links to your community." }
features.show_company_logo = { category = "features", type = "boolean", name = "Show Company Logo", description = "Show the company logo across the app." }
features.show_issue_report_link = { category = "features", type = "boolean", name = "Show Issue Report Link", description = "Show a link for reporting issues." }
features.show_avatar_editor_link = { category = "features", type = "boolean", name = "Show Avatar Editor Links", description = "Show links to avatar editors like Quilt." }
features.show_avatar_pipelines_link = { category = "features", type = "boolean", name = "Show Avatar Pipelines Links", description = "Show links to avatar pipeline info." }
features.show_model_collection_link = { category = "features", type = "boolean", name = "Show Model Collection Link", description = "Show link to a collection of models." }

features.enable_spoke = { category = "features", type = "boolean", internal = "true" }
features.show_join_us_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_discord_bot_link = { category = "features", type = "boolean", internal = "true" }
features.show_whats_new_link = { category = "features", type = "boolean", internal = "true" }
features.show_source_link = { category = "features", type = "boolean", internal = "true" }
features.show_newsletter_dialog = { category = "features", type = "boolean", internal = "true" }
features.show_feedback_ui = { category = "features", type = "boolean", internal = "true" }
features.show_issue_report_dialog = { category = "features", type = "boolean", internal = "true" }

images.logo = { category = "images", type = "file", name = "App Logo", description = "Logo used across the app." }
images.favicon = { category = "images", type = "file", name = "Favicon", description = "Icon for the app." }
images.company_logo = { category = "images", type = "file", name = "Company Logo", description = "Company logo used across the app." }
images.home_background = { category = "images", type = "file", name = "Home background", description = "Background image on the home page." }

colors.action-color = { category = "colors", type = "color", name = "Primary Color", description = "Used for call to action buttons and accents." }

links.terms_of_use = { category = "links", type = "string", name = "Terms of Use", description = "Link to your terms of use page."}
links.privacy_notice = { category = "links", type = "string", name = "Privacy Notice", description = "Link to your privacy page."}
links.controls = { category = "links", type = "string", name = "Controls Documentation", description = "Link to controls documentation."}
links.features = { category = "links", type = "string", name = "Features Documentation", description = "Link to features documentation."}
links.community = { category = "links", type = "string", name = "Community", description = "Link to your community."}
links.issue_report = { category = "links", type = "string", name = "Issue Report", description = "Link for reporting issues."}
links.promotion = { category = "links", type = "string", name = "Promotion Info", description = "Link to info about promotion info and licensing."}
links.remixing = { category = "links", type = "string", name = "Remixing Info", description = "Link to info about remixing info and licensing."}
links.model_collection = { category = "links", type = "string", name = "Model Collection", description = "Link to a collection of recommended models."}
