# App config schema
translations.en."home.hero_blurb" = { "category" = "translations", "type" = "string", "name" = "Hero Blurb", "description" = "Blurb displayed on the front page." }
translations.en."home.hero_blurb2" = { "category" = "translations", "type" = "string", "name" = "Hero Blurb", "description" = "Blurb displayed on the front page." }
features.disable_spoke = { "category" = "features", "type" = "boolean", "default" = "false", "name" = "Disable Spoke", "description" = "Hide links to Spoke." }
images.logo = { "category" = "images", "type" = "file", "name" = "App Logo", "description" = "Logo used across the app." }
images.home_background = { "category" = "images", "type" = "file" }
colors.primary-action = { "category" = "colors", "type" = "color" }
